# NixOS Configuration for Minecraft Server on OCI ARM
{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [./hardware-configuration.nix];

  # Boot loader configuration
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "minecraft";
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [
      22 # SSH
      25565 # Minecraft
    ];
  };

  # SSH with strict security
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
    };
  };

  # fail2ban for brute-force protection
  services.fail2ban = {
    enable = true;
    maxretry = 5;
    ignoreIP = [
      "127.0.0.1/8"
      "10.0.0.0/8"
    ];
  };

  # Root user with SSH keys
  users.users.root = {
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID5mdblREEnjNE8hqgViMurQOrDMPVeW46u9Jbw1oqwB bridger@nixos"
      "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIErSAuIjm52nSN7ZihpmbB6MDg+62WBs8sq+ME9B02bjAAAABHNzaDo= yubico-security-key-c-nfc-auth"
    ];
  };

  # Minecraft user
  users.users.minecraft = {
    isSystemUser = true;
    group = "minecraft";
    home = "/var/lib/minecraft";
    createHome = true;
  };
  users.groups.minecraft = {};

  # Minecraft Server systemd service
  systemd.services.minecraft-server = {
    description = "Vanilla Minecraft Server 1.21.4";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];

    serviceConfig = {
      Type = "simple";
      User = "minecraft";
      Group = "minecraft";
      WorkingDirectory = "/var/lib/minecraft";
      Restart = "always";
      RestartSec = "10s";

      # Setup script - downloads server.jar and creates initial configuration
      ExecStartPre = pkgs.writeShellScript "minecraft-setup.sh" ''
        cd /var/lib/minecraft

        # Download vanilla Minecraft server if not exists
        if [ ! -f server.jar ]; then
          echo "Downloading Minecraft Server 1.21.4..."
          ${pkgs.curl}/bin/curl -o server.jar https://piston-data.mojang.com/v1/objects/95495a7f485eedd84ce928cef5e223b757d2f764/server.jar
          echo "Server JAR downloaded successfully"
        fi

        # Accept EULA
        echo "eula=true" > eula.txt

        # Create server.properties if it doesn't exist
        if [ ! -f server.properties ]; then
          echo "Creating initial server.properties..."
          cat > server.properties << 'PROPS'
        # Minecraft Server Properties - Generated by NixOS
        server-port=25565
        max-players=20
        difficulty=normal
        gamemode=survival
        pvp=true
        motd=NixOS Minecraft Server on Oracle Cloud ARM
        online-mode=true
        enable-command-block=false
        spawn-protection=16
        max-world-size=29999984
        level-name=world
        level-seed=
        level-type=minecraft\:normal
        allow-nether=true
        allow-flight=false
        PROPS
          echo "Server properties created"
        fi

        echo "Minecraft server setup complete"
      '';

      # Start Minecraft server with optimized JVM flags
      ExecStart = "${pkgs.jdk21}/bin/java -Xmx10G -Xms10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -jar server.jar nogui";
    };
  };

  # Essential system administration tools
  environment.systemPackages = with pkgs; [
    vim
    git
    tmux
    htop
    btop
    curl
    wget
    jq
    ripgrep
    fd
    ncdu
    duf
    lsof
    strace
    tcpdump
    iftop
    jdk21 # Java 21 for Minecraft
  ];

  # NixOS system state version
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of your first install.
  system.stateVersion = "25.11";
}
