{
  description = "Advanced Portals Minecraft plugin with Velocity proxy support";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    advanced-portals-src = {
      url = "github:sekwah41/Advanced-Portals/main";
      flake = false;
    };
  };

  outputs = {
    self,
    nixpkgs,
    advanced-portals-src,
  }: let
    forAllSystems = nixpkgs.lib.genAttrs ["x86_64-linux" "aarch64-linux"];
  in {
    packages = forAllSystems (system: let
      pkgs = import nixpkgs {inherit system;};
    in {
      advanced-portals = pkgs.stdenv.mkDerivation {
        pname = "advanced-portals";
        version = "2.6.0-SNAPSHOT";
        src = advanced-portals-src;

        nativeBuildInputs = with pkgs; [jdk17 gradle];

        # Disable Gradle daemon and use offline mode after dependencies are fetched
        GRADLE_USER_HOME = ".gradle";

        buildPhase = ''
          # Create a writable gradle cache
          export GRADLE_USER_HOME=$PWD/.gradle

          # Build the plugin (skip tests for faster builds)
          gradle build -x test --no-daemon
        '';

        installPhase = ''
          mkdir -p $out/lib

          # The Spigot JAR contains all modules (Spigot, Velocity, Bungee, ProxyCore)
          # This is the unified JAR that works for both Paper and Velocity
          cp spigot/build/libs/Advanced-Portals-Spigot-*.jar $out/lib/advanced-portals.jar
        '';

        # Allow network access during build for Gradle dependencies
        __noChroot = true;
      };

      default = self.packages.${system}.advanced-portals;
    });

    # Helper function to generate config.yaml with custom settings
    lib = {
      mkConfig = {
        enableProxySupport ? true,
        defaultTriggerBlock ? "NETHER_PORTAL",
        selectorMaterial ? "IRON_AXE",
        portalProtection ? true,
        portalProtectionArea ? 5,
        ...
      }: ''
        # Advanced Portals Configuration
        # Generated by Nix

        enableProxySupport: ${
          if enableProxySupport
          then "true"
          else "false"
        }
        defaultTriggerBlock: ${defaultTriggerBlock}
        selectorMaterial: ${selectorMaterial}
        portalProtection: ${
          if portalProtection
          then "true"
          else "false"
        }
        portalProtectionArea: ${toString portalProtectionArea}

        # Warp effects
        warpEffect: true
        warpParticles: PORTAL
        warpSound: BLOCK_PORTAL_TRAVEL

        # Portal block settings
        showBungeeMessage: true
        portalInformationDisplayTime: 60

        # Default portal trigger block
        stopWaterFlow: true

        # Portal creation settings
        throwbackStrength: 0.7

        # Advanced settings
        commandDelay: 0
        playFailSound: true

        # Permissions
        useOnlySpecialAxe: false

        # Portal blocks
        enableCustomPortalBlocks: true
      '';
    };
  };
}
