{
  description = "Advanced Portals Minecraft plugin with Velocity proxy support";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    advanced-portals-src = {
      url = "github:sekwah41/Advanced-Portals/main";
      flake = false;
    };
  };

  outputs = {
    self,
    nixpkgs,
    advanced-portals-src,
  }: let
    forAllSystems = nixpkgs.lib.genAttrs ["x86_64-linux" "aarch64-linux"];
  in {
    packages = forAllSystems (system: let
      pkgs = import nixpkgs {inherit system;};
    in {
      advanced-portals = pkgs.stdenv.mkDerivation rec {
        pname = "advanced-portals";
        version = "2.6.0-SNAPSHOT";
        src = advanced-portals-src;

        nativeBuildInputs = with pkgs; [jdk17 gradle.unwrapped];

        # Disable Gradle setup hook that forces offline mode
        dontUseGradleSetupHook = true;

        # Patch build.gradle to remove IDE-only plugin and config that causes issues in Nix
        patchPhase = ''
          sed -i "/id 'org.jetbrains.gradle.plugin.idea-ext'/d" build.gradle

          # Remove the idea { project { settings { ... } } } block (lines 90-96)
          sed -i '/^idea {$/,/^}$/d' build.gradle
        '';

        # Use a Fixed-Output Derivation to allow network access for Gradle
        buildPhase = ''
          export GRADLE_USER_HOME=$PWD/.gradle

          # Build the plugin (skip tests for faster builds)
          # Note: FOD allows network access for downloading dependencies
          # Create empty permissions.yml to satisfy generateTemplates task
          mkdir -p spigot/build/generated/resources
          touch spigot/build/generated/resources/permissions.yml

          # Skip permission generation tasks that have dependency issues
          gradle :spigot:build -x test -x compilePermissionsGen -x generatePermissionsYaml --no-daemon --refresh-dependencies
        '';

        installPhase = ''
          mkdir -p $out/lib

          # The Spigot JAR contains all modules (Spigot, Velocity, Bungee, ProxyCore)
          # This is the unified JAR that works for both Paper and Velocity
          cp spigot/build/libs/Advanced-Portals-Spigot-*.jar $out/lib/advanced-portals.jar
        '';

        # Fixed-Output Derivation: allows network access during build
        outputHashMode = "recursive";
        outputHashAlgo = "sha256";
        outputHash = "sha256-RWqLbZRvF82NW3th7G3uAafL7+Gczjf+LsY6u5z1raw=";
      };

      default = self.packages.${system}.advanced-portals;
    });

    # Helper function to generate config.yaml with custom settings
    lib = {
      mkConfig = {
        enableProxySupport ? true,
        defaultTriggerBlock ? "NETHER_PORTAL",
        selectorMaterial ? "IRON_AXE",
        portalProtection ? true,
        portalProtectionArea ? 5,
        ...
      }: ''
        # Advanced Portals Configuration
        # Generated by Nix

        enableProxySupport: ${
          if enableProxySupport
          then "true"
          else "false"
        }
        defaultTriggerBlock: ${defaultTriggerBlock}
        selectorMaterial: ${selectorMaterial}
        portalProtection: ${
          if portalProtection
          then "true"
          else "false"
        }
        portalProtectionArea: ${toString portalProtectionArea}

        # Warp effects
        warpEffect: true
        warpParticles: PORTAL
        warpSound: BLOCK_PORTAL_TRAVEL

        # Portal block settings
        showBungeeMessage: true
        portalInformationDisplayTime: 60

        # Default portal trigger block
        stopWaterFlow: true

        # Portal creation settings
        throwbackStrength: 0.7

        # Advanced settings
        commandDelay: 0
        playFailSound: true

        # Permissions
        useOnlySpecialAxe: false

        # Portal blocks
        enableCustomPortalBlocks: true
      '';
    };
  };
}
